#!/bin/bash

app='rainloop'	# This could never work with multi-instance. Need to find a better way
domain=$1
final_path=/var/www/$app/app

sudo rm $final_path/data/_data_/_default_/domains/$domain.ini
